api/urls.py
from django.urls import path
from api import views, payments


urlpatterns = [
    path('terms/', views.TermAndConditionAPI.as_view()),
    path('legal-terms/', views.LegalTermAPI.as_view()),
    path('privacy-policy/', views.PrivacyPolicyAPI.as_view()),
    path('admin-contact/', views.AdminContactAPI.as_view()),
    path('payment-terms/', views.PaymentTermAPI.as_view()),
    path('user-notifications/', views.UserNotificationList.as_view()),
    path('user-notifications/<str:pk>/', views.UserNotificationDetail.as_view()),
    path('device-token/', views.DeviceTokenView.as_view()),
    path('check-email/', views.CheckEmail.as_view()),
    path('register/', views.RegistrationAPI.as_view()),
    path('login/', views.LoginAPI.as_view()),
    path('refresh-token/', views.RefreshTokenView.as_view()),
    path('profile/', views.ProfileAPI.as_view()),
    path('password/', views.PasswordAPI.as_view()),
    path('users/', views.CustomUserList.as_view()),
    path('users/<str:pk>/', views.CustomUserDetail.as_view()),
    path('payment-sources/', payments.PaymentMethodAPI.as_view()),
    path('security-firms/', views.SecurityFirmList.as_view()),
    path('security-firms/<str:pk>/', views.SecurityFirmDetail.as_view()),
    path('hospitalities/', views.HospitalityList.as_view()),
    path('hospitalities/<str:pk>/', views.HospitalityDetail.as_view()),
    path('user-documents/', views.UserDocumentList.as_view()),
    path('user-documents/<str:pk>/', views.UserDocumentDetail.as_view()),
    path('license-types/', views.LicenseTypeList.as_view()),
    path('license-types/<str:pk>/', views.LicenseTypeDetail.as_view()),
    path('venues/', views.VenueList.as_view()),
    path('venues/<str:pk>/', views.VenueDetail.as_view()),
    path('venue-documents/', views.VenueDocumentList.as_view()),
    path('venue-documents/<str:pk>/', views.VenueDocumentDetail.as_view()),
    path('assign-security-staff/', views.SecurityStaffAssignment.as_view()),
    path('assign-venue-staff/', views.VenueStaffAssignment.as_view()),
    path('subscription/', payments.SubscriptionView.as_view()),
    path('incident-actions/', views.IncidentActionList.as_view()),
    path('incident-actions/<str:pk>/', views.IncidentActionDetail.as_view()),
    path('incidents/', views.IncidentList.as_view()),
    path('incidents/<str:pk>/', views.IncidentDetail.as_view()),
    path('incident-persons/', views.IncidentPersonList.as_view()),
    path('incident-persons/<str:pk>/', views.IncidentPersonDetail.as_view()),
    path('incident-media/', views.IncidentMediaList.as_view()),
    path('incident-media/<str:pk>/', views.IncidentMediaDetail.as_view()),
    path('venue-managers/', views.ManagerList.as_view()),
    path('incident-logs/', views.IncidentLogList.as_view()),
    path('growth-stat/', views.GrowthStat.as_view()),
    path('service-providers/', views.ServiceProviderList.as_view()),
    path('service-provider-allocations/', views.ServiceProviderAllocation.as_view()),
    path('verify-license/', views.VerifyLicenseAPI.as_view()),
    path('covid-checklists/', views.CovidChecklistList.as_view()),
    path('covid-checklists/<str:pk>/', views.CovidChecklistDetail.as_view()),
    path('checklist-images/', views.ChecklistImageList.as_view()),
    path('checklists_new/', views.ChecklistNewView.as_view()),
    path('checklists_new_submit/', views.ChecklistNewSubmitView.as_view()),
    path('activity_list/', views.ActivityListView.as_view()),



]

star_compliance/urls.py
from django.contrib import admin
from django.urls import path, include
from api.payments import StripeWebhook
from django.contrib.auth import views as auth_views
from api.views import DownloadReportView

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('admin/', admin.site.urls),
    path('api/v1/', include('api.urls')),
    path('stripe-webhook/', StripeWebhook.as_view()),
    path('idp/', include('djangosaml2idp.urls')),
    path('download-report/', DownloadReportView.as_view()),
]

api/models.py
import uuid

from ckeditor.fields import RichTextField
from django.contrib.auth.models import AbstractUser, UserManager
from django.contrib.postgres.fields import ArrayField, JSONField
from django.core.validators import RegexValidator
from django.db import models
from django.contrib.postgres.fields import JSONField

from api.choices import (DeviceType, Gender, NotificationType,
                         SubscriptionUserType, UserType, IncidentStatus,
                         IncidentLogType, CovidChecklistType)
from api.upload_handlers import (handle_user_doc, handle_user_image,
                                 handle_venue_doc, handle_venue_logo, handle_incident_files,
                                 handle_checklist_files)
from djangosaml2idp.models import ServiceProvider


class BaseModel(models.Model):
    id = models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True)
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True


class BaseOrganisation(BaseModel):
    name = models.CharField(max_length=300)
    email = models.EmailField(null=True, blank=True)
    phone = models.CharField(max_length=50, null=True, blank=True)

    class Meta:
        abstract = True


class Subscription(BaseModel):
    plan_id = models.CharField(max_length=250)
    subscription_id = models.CharField(max_length=250, db_index=True)
    status = models.CharField(max_length=100, null=True)

    class Meta:
        abstract = True


class LegalTerm(BaseModel):
    '''To show on every login'''
    text = RichTextField()


class TermAndCondition(BaseModel):
    text = RichTextField()


class PaymentTerm(BaseModel):
    text = RichTextField()


class PrivacyPolicy(BaseModel):
    text = RichTextField()


class AdminContact(BaseModel):
    email = models.EmailField()
    phone_number = models.CharField(max_length=50)

    def __str__(self):
        return self.email


class SecurityFirm(BaseOrganisation):
    stripe_customer_id = models.TextField(null=True, blank=True)
    license_type = models.ForeignKey('LicenseType', on_delete=models.PROTECT, null=True)
    subscription_current_period_end = models.DateTimeField(null=True, blank=True)
    current_subscription_id = models.CharField(max_length=250, null=True, blank=True)
    # Possible values are incomplete, incomplete_expired, trialing, active,
    # past_due, canceled, or unpaid.
    current_subscription_status = models.CharField(max_length=100, null=True, blank=True)
    sso_service_provider = models.ForeignKey(
        ServiceProvider, on_delete=models.CASCADE, null=True, blank=True)

    class Meta:
        ordering = ('name',)


class SecurityFirmSubscription(Subscription):
    security_firm = models.ForeignKey(SecurityFirm, on_delete=models.CASCADE)


class Hospitality(BaseOrganisation):
    stripe_customer_id = models.TextField(null=True, blank=True)
    sso_service_provider = models.ForeignKey(
        ServiceProvider, on_delete=models.CASCADE, null=True, blank=True)

    class Meta:
        ordering = ('name',)


class CustomUserManager(UserManager):
    def get_queryset(self):
        return super().get_queryset().select_related('security_firm', 'hospitality')

    def _create_user(self, email, password, **extra_fields):
        """
        Create and save a user with the given username, email, and password.
        """
        email = self.normalize_email(email).lower()
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email=None, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')

        return self._create_user(email, password, **extra_fields)


class CustomUser(AbstractUser):
    """
    is_superuser tells if user is app admin
    for all the other users, user_type field is used.
    """
    id = models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True)
    username = None
    user_type = models.CharField(max_length=20, choices=[x.value for x in UserType])
    email = models.EmailField(
        error_messages={"unique": "A user with this email already exists"},
        unique=True,
        db_index=True,
        max_length=150
    )
    notification_setting = models.BooleanField(default=True)
    unread_notification_count = models.PositiveIntegerField(default=0)
    profile_picture = models.ImageField(
        upload_to=handle_user_image, null=True, blank=True)
    security_firm = models.ForeignKey(
        SecurityFirm,
        on_delete=models.CASCADE,
        null=True,
        blank=True)
    hospitality = models.ForeignKey(
        Hospitality,
        on_delete=models.CASCADE,
        null=True,
        blank=True)
    address = models.CharField(max_length=500, null=True, blank=True)
    suburb = models.CharField(max_length=150, null=True, blank=True)
    state = models.CharField(max_length=150, null=True, blank=True)
    postcode = models.CharField(max_length=50, null=True, blank=True)
    phone_number = models.CharField(max_length=50, null=True)
    emergency_contact_name = models.CharField(max_length=100, null=True, blank=True)
    emergency_contact_phone = models.CharField(max_length=50, null=True, blank=True)
    # For all types of users. Competency cards in case of hospitality users
    # and security license in case of security user
    license_number = models.CharField(max_length=150, null=True, blank=True)
    # For all types of users. Competency cards in case of hospitality users
    # and security license in case of security user
    license_type = models.CharField(max_length=150, null=True, blank=True)
    # For all types of users. Competency cards in case of hospitality users
    # and security license in case of security user
    license_expiry = models.DateField(null=True, blank=True)
    is_license_verified = models.BooleanField(
        default=False,
        help_text='This tells that the license details were retrived from nsw gov API')
    is_license_active = models.BooleanField(
        default=False,
        help_text='This tells that the license details are from the NSW Gov API and it is not expired')
    sso_service_provider = models.ForeignKey(
        ServiceProvider, on_delete=models.CASCADE, null=True, blank=True)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []
    objects = CustomUserManager()

    class Meta:
        ordering = ('first_name',)


class DeviceToken(BaseModel):
    device_type = models.CharField(max_length=10, choices=[x.value for x in DeviceType])
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    token = models.TextField()


class UserNotification(BaseModel):
    notification_type = models.CharField(
        max_length=20, choices=[
            x.value for x in NotificationType])
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    title = models.CharField(max_length=250)
    body = models.CharField(max_length=500)
    id_data = models.CharField(max_length=50, null=True)
    is_read = models.BooleanField(default=False)

    class Meta:
        ordering = ('-created_at',)


class UserDocument(BaseModel):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE, null=True)
    document = models.FileField(upload_to=handle_user_doc)

    class Meta:
        ordering = ('-created_at',)


class LicenseType(BaseModel):
    name = models.CharField(max_length=100, unique=True)
    amount = models.DecimalField(max_digits=6, decimal_places=2, null=True)
    subscription_plan_id = models.CharField(max_length=200, unique=True)
    subscription_type = models.CharField(
        max_length=2, choices=[
            x.value for x in SubscriptionUserType])
    description = models.TextField()

    def __str__(self):
        return self.name

    class Meta:
        ordering = ('amount',)


class Venue(BaseModel):
    # created_by - hospitality admin of the related hospitality
    hospitality = models.ForeignKey(Hospitality, on_delete=models.CASCADE)
    logo = models.ImageField(upload_to=handle_venue_logo, null=True, blank=True)
    venue_admins = models.ManyToManyField(CustomUser, related_name='va_venues')
    venue_managers = models.ManyToManyField(CustomUser, related_name='vm_venues')
    venue_staff = models.ManyToManyField(CustomUser, related_name='vs_venues')
    security_staff = models.ManyToManyField(CustomUser, related_name='ss_venues')
    name = models.CharField(
        max_length=250,
        null=True,
        unique=True,
        error_messages={"unique": "A Venue with this name exists"},)
    address = models.CharField(max_length=500, null=True)
    suburb = models.CharField(max_length=150, null=True)
    state = models.CharField(max_length=150, null=True)
    postcode = models.CharField(max_length=50, null=True)
    website = models.URLField(null=True)
    abn = models.CharField(
        max_length=11,
        validators=[
            RegexValidator(r'^\d{11}$')],
        null=True)
    license_type = models.ForeignKey(LicenseType, on_delete=models.PROTECT, null=True)
    license_number = models.CharField(max_length=150, null=True, blank=True)
    license_validity_date = models.DateField(null=True, blank=True)
    phone = models.CharField(max_length=50, null=True)
    email = models.EmailField(null=True, blank=True)

api/templates/reports/covid_checklist.html
{% load tz %}
{% timezone "Australia/Sydney" %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Star Compliance</title>
  <link href="https://fonts.googleapis.com/css?family=Montserrat:400,500,600,700,800&display=swap" rel="stylesheet">
  <style>
    body {
      font-family: 'Montserrat', sans-serif;
    }

    .page_table2_main {
      page-break-before: always;
      width: 99%;
      max-width: 7.5in;
      table-layout: fixed;
      /* padding: 25px; */
      margin: 0 auto;
      /* border: 1px solid; */
      font-size: 14px;
      /* page-break-after: always; */

    }

    .page_table2_list {
      /* page-break-before: always; */
      width: 99%;
      max-width: 7.5in;
      table-layout: fixed;
      /* padding: 25px; */
      margin: 0 auto;
      /* border: 1px solid; */
      font-size: 14px;
      page-break-after: always;

    }

    .venue_table {
      width: 100%;
    }

    .venue_table td {
      max-width: 1.5in;
      padding: 2px 8px;
      height: unset;
      line-height: unset;
      vertical-align: top;
      text-align: center;
      font-size: 13px;
    }

    .venue_table td h5 {
      margin: 10px 0px;
    }

    .venue_table {
      padding: 0px;
      margin: 0px;
      margin-top: 0px;
    }

    .venue_table.tl_f td h5 {
      margin-top: 25px;
    }

    .fixed_table_layout {
      table-layout: fixed;
    }

    .main_heading {
      color: #B9BED1;
      font-weight: bold;
      font-size: 17px;
      text-transform: uppercase;
      margin-top: 50px;
    }

    .sub_heading p {

      color: #B9BED1;
      font-weight: bold;
      font-size: 14px;
      margin-right: 7px;

    }

    .sub_heading span {

      font-weight: 600;
      margin: 20px 0px;
      display: block;
      padding-right: 85px;
      font-size: 13px;

    }

    .sub_heading_ul {
      padding: 0px;
    }

    .sub_heading_ul li {
      padding: 10px 0px;
      color: #000;
      padding-right: 1.1in;
      list-style-type: none;
      position: relative;
      font-size: 13px;
      font-weight: 500
    }

    .sub_heading_ul .checked_li::after {
      content: "";
      background-image: url("data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADMAAAAjCAYAAAA5dzKxAAAACXBIWXMAAAsTAAALEwEAmpwYAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAIBSURBVHgB1dlPLgNhGMfx3/POxtLSkgUJsXEC3SISToATGC7QcQEZJ+AGiEi3bsDOgkWPMOvS9zW/0RbR6sz7Z0y/iQSl7afTdt73qWBGer6LWypSxzCmlf84n391BfLQ7+mz1f20y78RzEAvnbittSQTLu6+weyv76RPjcdMgQzLdM9sRGhwJSFsDiLSWEwFSJEIFhr5NKsKGdY4jC0kL1Pjfvt4Hc/jH3KA5Jmb0ZF57sSLkUbbQPbw+T7O5+HDO8zF2nZ6g8C5QYD83WypODKvnZMDpeUxhxxiAGHGoBUZuX7pnLYRMGeIluLEKTwihOAbYlxKSbK8dX4Gz3mB7J4n/F5FWvFRn/oa0dokvo+QTwhTBsVap+Q/+wP5hjC+ZhZRIR+gEBBGTIaKuYBCQZjSxtzCIhtQSAhTkSCF9ZWXB4WGMLWS7wM0zBGsb2Q6qA4I+1oB3MeHCnIJyyadh+qCsB8LTd+gOiHs16rZF6huCBu7BXAFcYHKdR0ss4EUtzvpAleQbbYQ9ufmrG6QC4RN3WnWBXKFsFLb5tAgHxBWegYQCsQT9upOegUPVRpo+Ab5hLDK0xlfIN8QZjVqcgWFgDDruZktKBSEOQ0Bq4JCQpjzRLMsKDSEKTjGOzjYD03afmd1QJi3WTPnb+gjUSKb+BySZJKPTPs9jD7ZCt0HEPd/x6wdMusAAAAASUVORK5CYII=");
      background-size: 100% 100%;
      display: inline-block;
      height: 8px;
      width: 12px;
      position: absolute;
      right: 50px;
      top: 12px;
      border-top: none;
      border-right: none;
    }

    .sub_heading_ul .unchecked_li::after {
      content: "";
      border-top: none;
      border-right: none;
    }

    .upload_photos td {
      padding: .1in;
    }

    .upload_photos img {
      width: 2.25in;
      height: 1.5in;
      background: #E3E8F0;
      border-radius: 12px;
      object-fit: cover;
    }

    .media_container {
      width: calc(50% - 20px);
      border-radius: 4px;
      background-color: #F0F2F7;
      display: inline-block;
      height: 215px;
      object-fit: cover;
      margin: 10px 5px;
      margin-bottom: 0px;
      margin-top: 22px;
    }

    .media {
      height: 100%;
      overflow: hidden;
      align-items: center;
      display: block;
      margin: 0 auto;
      top: 50%;
      position: relative;
      transform: translateY(-50%);
      -webkit-transform: translateY(-50%);
      -ms-transform: translateY(-50%);
    }

    .va_t td {
      vertical-align: top;
    }

    .detail_table {
      width: 100%;
      border: none;
      border-collapse: collapse;
    }

    .detail_table td {
      padding: 12px 15px;
      text-align: center;
      font-size: 14px;
      border: none;
      outline: none;
      box-shadow: none;
      border-collapse: collapse;
    }

    .detail_table th {
      padding: 12px;
    }

    .detail_table tr:nth-child(odd) {
      background-color: #F0F2F7;
    }

    thead tr {
      background-color: #fff !important;
    }

    .m_20 {
      margin-top: 15px auto;
      margin-bottom: 20px auto;
      margin-right: 20px auto;
      margin-left: 20px auto;
    }

    .mb_2 {
      margin-bottom: 2px;
    }

    .hr {
      border-top: 1px solid #000;
      margin: 20px auto;
    }
  </style>
</head>

<body>

  <table class="page_table2_main">

    <tr>
      <td colspan="2" class="">
        <h2 style="text-transform: uppercase;">{{checklist_type}}</h2>
      </td>
    </tr>
    <tr>
      <td colspan="2">
        <hr class="hr m_20 mb_2" />
      </td>
    </tr>
    <tr>
      <td colspan="2">
        <table class="venue_table fixed_table_layout">
          <tr>
            <td>
              <h5>VENUE</h5>
            </td>
            <td>
              <h5>DATE RANGE</h5>
            </td>
          </tr>
          <tr>
            <td>
              {{venue.name}}
              <br>
              LIC: {{venue.license_number}}
            </td>
            <td>
              {% if from_date and to_date %}
              {{from_date|date:"d/m/Y"}} to {{to_date|date:"d/m/Y"}}
              {% elif from_date and not to_date %}
              From {{from_date|date:"d/m/Y"}}
              {% elif to_date and not from_date %}
              Till {{to_date|date:"d/m/Y"}}
              {% else %}
              All
              {% endif %}
            </td>
          </tr>
        </table>
      </td>
    </tr>
    <tr>
      <td colspan="2">
        <hr class="hr m_20 mb_2" />
      </td>
    </tr>
  </table>
  <table class="page_table2_list detail_table">
    <thead>
      <th>
        DATE
      </th>

      <th>
        TIME
      </th>
      <th>
        STAFF
      </th>
      <th>
        ROLE
      </th>

    </thead>
    <tbody>
      {% for i in checklists %}
      <tr>

        <td>
          {{i.created_at|date:"d/m/Y"}}
        </td>
        <td>
          {{i.created_at|time:"h:i A"}}
        </td>
        <td>
          {{i.user.first_name}} {{i.user.last_name}}
        </td>
        <td>
          {{i.user.get_user_type_display}}
        </td>
      </tr>
      {% endfor %}

    </tbody>
  </table>

  {% for j in checklists %}
  <table class="page_table2_main">

    <tr>
      <td colspan="2">
        <hr class="hr m_20 mb_2" />
      </td>
    </tr>
    <tr>
      <td colspan="2">
        <table class="venue_table fixed_table_layout">
          <tr>
            <td>
              <h5>VENUE</h5>
            </td>
            <td>
              <h5>STAFF</h5>
            </td>
            <td>
              <h5>ROLE</h5>
            </td>
            <td>
              <h5>DATE / TIME</h5>
            </td>
            <td>
              <h5>ATTACHMENTS</h5>
            </td>
          </tr>
          <tr>
            <td>
              {{venue.name}}
              <br>
              LIC: {{venue.license_number}}
            </td>
            <td>
              {{j.user.first_name}} {{j.user.last_name}}
            </td>
            <td>
              {{j.user.get_user_type_display}}
            </td>
            <td>
              {{j.created_at}}
            </td>
            <td>
              {{j.attachments_count}}
            </td>
          </tr>
        </table>
      </td>
    </tr>
    <tr>
      <td colspan="2">
        <hr class="hr m_20 mb_2" />
      </td>
    </tr>
    {% for section in j.checklist_json.sections %}
    <tr>
      <td colspan="2">
        <p class="main_heading">{{section.title|default:""}}</p>
      </td>
    </tr>
    <tr>
      <td colspan="2">
        <hr class="hr m_20 mb_2" />
      </td>
    </tr>
    {% for subsection in section.subsections %}
    {% if forloop.last %}
    {% if forloop.counter0|divisibleby:2 %}
    <tr class="va_t">
      <td class="sub_heading">
        <p>{{subsection.label|default:""}}</p>
        <ul class="sub_heading_ul">
          {% for choice in subsection.choices %}
          {% if choice.selected %}
          <li class="checked_li">
            {{choice.choice}}
          </li>
          {% else %}
          <li class="unchecked_li">
            {{choice.choice}}
          </li>
          {% endif %}
          {% endfor %}
        </ul>
      </td>
    </tr>
    {% else %}
    <td class="sub_heading">
      <p>{{subsection.label|default:""}}</p>
      <ul class="sub_heading_ul">
        {% for choice in subsection.choices %}
        {% if choice.selected %}
        <li class="checked_li">
          {{choice.choice}}
        </li>
        {% else %}
        <li class="unchecked_li">
          {{choice.choice}}
        </li>
        {% endif %}
        {% endfor %}
      </ul>
    </td>
    </tr>
    {% endif %}
    {% else %}
    {% if forloop.counter0|divisibleby:2 %}
    <tr class="va_t">
      <td class="sub_heading">
        <p>{{subsection.label|default:""}}</p>
        <ul class="sub_heading_ul">
          {% for choice in subsection.choices %}
          {% if choice.selected %}
          <li class="checked_li">
            {{choice.choice}}
          </li>
          {% else %}
          <li class="unchecked_li">
            {{choice.choice}}
          </li>
          {% endif %}
          {% endfor %}
        </ul>
      </td>
      {% else %}
      <td class="sub_heading">
        <p>{{subsection.label|default:""}}</p>
        <ul class="sub_heading_ul">
          {% for choice in subsection.choices %}
          {% if choice.selected %}
          <li class="checked_li">
            {{choice.choice}}
          </li>
          {% else %}
          <li class="unchecked_li">
            {{choice.choice}}
          </li>
          {% endif %}
          {% endfor %}
        </ul>
      </td>
    </tr>
    {% endif %}
    {% endif %}
    {% endfor %}
    {% endfor %}
    {% if j.checklistimage_set.all %}
    <tr>
      <td colspan="2">
        <h4 style="color: #B9BED1;">Uploaded Photos</h4>
      </td>
    </tr>
    {% for z in j.checklistimage_set.all %}
    {% if forloop.counter0|divisibleby:2 %}
    {% if forloop.last %}
    <tr>
      <td>
        <div class="media_container"> <img class="media" src="{{z.image.url}}" alt="star compliance" /></div>
      </td>
    </tr>
    {% else %}
    <tr>
      <td>
        <div class="media_container"> <img class="media" src="{{z.image.url}}" alt="star compliance" /></div>
      </td>
      {% endif %}
      {% else %}
      <td>
        <div class="media_container"> <img class="media" src="{{z.image.url}}" alt="star compliance" /></div>
      </td>
    </tr>
    {% endif %}
    {% endfor %}
    {% endif %}
  </table>
  {% endfor %}

</body>

</html>
{% endtimezone %}

api/templates/reports/covid_checklist_header.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Star Compliance</title>
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,500,600,700,800&display=swap" rel="stylesheet">
<style>
    body
    {
        font-family: 'Montserrat', sans-serif;
    }
    .page_table2_main
    {
        width: 100%;
        max-width: 11.5in;
        table-layout: fixed;
        padding: 20px;
        margin: 0 auto;
        font-size: 14px;
    }
    .logo
    {
        max-width: 80px;
    }
  
</style>
</head>
<body>
    <table class="page_table2_main">
        <tr>
            <td>
                <img class="logo" src="https://star-compliance-assets.s3-ap-southeast-2.amazonaws.com/Layer_2.png" alt="star logo" />
            </td>
           
            <td>
                <h2 style="text-align: right; text-transform: uppercase;">Checklist<br>Report</h2>
            </td>
        </tr>
       
    </table>
</body>
</html>

api/templates/reports/incident_detail_header.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Star Compliance</title>
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,500,600,700,800&display=swap" rel="stylesheet">
<style>
    body 
    {
        font-family: 'Montserrat', sans-serif;
    }
    .page_table2_main
    {
        width: 100%;
        max-width: 11.5in;
        table-layout: fixed;
        padding: 20px;
        margin: 0 auto;
        font-size: 14px;
    }
    .logo
    {
        max-width: 65px;
    }
  
</style>
</head>
<body>
    <table class="page_table2_main">
        <tr>
            <td>
                <img class="logo" src="https://star-compliance-assets.s3-ap-southeast-2.amazonaws.com/Layer_2.png" alt="star logo" />
            </td>
           
            <td>
                <h2 style="text-align: right;">INCIDENT<br>REPORT</h2>
            </td>
        </tr>
       
    </table>
</body>
</html>